const { chromium } = require("playwright");
const assert = require("node:assert/strict");

(async () => {
  const browser = await chromium.launch({ headless: true, channel: "msedge" });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  const chapter = { _id: "111111111111111111111111", name: "Motion", chapterNumber: 2 };
  const topics = ["2.10", "2.3.5", "2.3"].map((topicNumber, i) => ({ _id: String(i + 2).repeat(24), name: "Topic " + topicNumber, topicNumber, videoUrl: "https://www.youtube.com/watch?v=aqz-KE-bpKQ" }));
  let startPayload;
  let successfulTest = false;
  const question = { type: "scenario_mcq", scenario: { _id: "scenario1", title: "Motion scenario", scenarioText: "A student observes a moving object." }, _id: "q1", questionText: "Which answer is correct?", options: [{ key: "A", text: "First answer" }, { key: "B", text: "Second answer" }], correctOption: "A" };
  const attempt = { _id: "attempt1", assessment: { title: "Motion MCQ test" }, status: "in_progress", expiresAt: new Date(Date.now() + 600000).toISOString(), answers: Array.from({ length: 5 }, (_, i) => ({ question: { ...question, _id: "q" + (i + 1) } })) };
  await page.route("http://localhost:5000/api/**", async route => {
    const url = new URL(route.request().url());
    const headers = { "access-control-allow-origin": "*", "access-control-allow-headers": "*", "access-control-allow-methods": "*" };
    if (route.request().method() === "OPTIONS") return route.fulfill({ status: 204, headers });
    let data = {};
    if (url.pathname.endsWith("/chapters")) data = { chapters: [chapter] };
    else if (url.pathname.includes("/topics/chapter/")) data = { chapter, topics };
    else if (url.pathname.endsWith("/questions/topic-questions")) data = { topic: { name: "Topic 2.3" }, questions: [{ _id: "q1", questionText: url.searchParams.get("contentType") === "long_question" ? "Explain motion." : "Define motion.", examYear: 2024, examSession: "morning" }] };
    else if (url.pathname.endsWith("/attempts/start")) {
      startPayload = route.request().postDataJSON();
      if (successfulTest) return route.fulfill({ headers, contentType: "application/json", body: JSON.stringify({ attempt }) });
      return route.fulfill({ headers, status: 404, contentType: "application/json", body: JSON.stringify({ message: "No published MCQs have been added here yet." }) });
    } else if (url.pathname.endsWith("/attempts/attempt1/submit")) data = { attempt: { _id: "attempt1" } };
    else if (url.pathname.endsWith("/attempts/attempt1/result")) data = { attempt: { ...attempt, status: "submitted", score: 1, totalMarks: 1, percentage: 100, timeTakenSeconds: 5, passStatus: "pass" } };
    else if (url.pathname.endsWith("/admin/me")) data = { admin: { name: "Teacher", role: "super_admin" } };
    else if (url.pathname.endsWith("/questions")) data = { questions: [] };
    else if (url.pathname.endsWith("/scenarios/list")) data = { scenarios: [] };
    else if (url.pathname.endsWith("/boards")) data = { boards: [] };
    else if (url.pathname.endsWith("/classes")) data = { classes: [] };
    else if (url.pathname.endsWith("/groups")) data = { groups: [] };
    else if (url.pathname.endsWith("/students/me")) data = { student: { name: "Test Student" } };
    await route.fulfill({ headers, contentType: "application/json", body: JSON.stringify(data) });
  });
  const base = process.env.TEST_URL || "http://127.0.0.1:5173";
  const path = "/chapters?board=Punjab&class=10&group=Science&subject=Physics&subjectId=999999999999999999999999";
  await page.goto(base + path);
  const toggle = page.getByRole("button", { name: /Motion/ });
  await toggle.click().catch(async error => { console.log(await page.locator("body").innerText(), errors); throw error; });
  const rows = page.locator("article ol li");
  await rows.last().waitFor();
  assert.deepEqual(await rows.locator("a").filter({ hasText: /^2\./ }).count(), 3);
  assert.deepEqual(await rows.locator("a span:first-child").allTextContents(), ["2.3", "2.3.5", "2.10"]);
  assert.equal(await rows.getByRole("link", { name: /notes/i }).count(), 0);
  assert.equal(await rows.getByRole("link", { name: "Test", exact: true }).count(), 3);
  const bounds = await rows.evaluateAll(items => items.map(item => { const r = item.getBoundingClientRect(); return { y: r.y, bottom: r.bottom }; }));
  assert.ok(bounds[1].y >= bounds[0].bottom);
  await page.screenshot({ path: "tests/chapters-desktop.png", fullPage: true });
  await rows.first().getByRole("link", { name: "Video", exact: true }).click();
  await page.locator("iframe").waitFor();
  assert.equal(await page.getByRole("heading", { name: "Topic 2.3", exact: true }).count(), 1);
  await page.goto(base + path);
  await toggle.click();
  await rows.first().getByRole("link").first().click();
  await page.getByText("Explain motion.", { exact: true }).waitFor();
  assert.equal(await page.getByRole("listbox").count(), 0);
  assert.equal(await page.locator("select").count(), 0);
  await page.getByRole("button", { name: "Short Questions", exact: true }).click();
  await page.getByText("Define motion.", { exact: true }).waitFor();
  await page.getByRole("link", { name: "Back to chapters" }).click();
  assert.ok(page.url().includes("board=Punjab"));
  await page.locator("article").getByRole("link", { name: "Test", exact: true }).click();
  await page.waitForURL("**/login");
  await page.evaluate(() => localStorage.setItem("studentToken", "fixture"));
  await page.goto(base + "/tests/start?chapter=" + chapter._id);
  await page.getByRole("alert").waitFor();
  assert.equal(startPayload.chapter, chapter._id);
  assert.equal(startPayload.topic, undefined);
  await page.goto(base + "/tests/start?topic=" + topics[2]._id);
  await page.getByRole("alert").waitFor();
  assert.equal(startPayload.topic, topics[2]._id);
  assert.equal(startPayload.chapter, undefined);
  successfulTest = true;
  await page.goto(base + "/tests/start?chapter=" + chapter._id);
  await page.getByText("Read this scenario and answer the following 5 questions.", { exact: true }).waitFor();
  await page.getByRole("button", { name: "Next", exact: true }).click();
  await page.getByText("Scenario question 2 of 5", { exact: true }).waitFor();
  await page.getByRole("button", { name: "A First answer" }).click();
  await page.getByRole("button", { name: "Submit", exact: true }).click();
  await page.getByRole("button", { name: "Submit Test", exact: true }).last().click();
  await page.waitForURL("**/tests/result/attempt1");
  await page.getByRole("heading", { name: "100%" }).waitFor();
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto(base + path);
  await toggle.click();
  await rows.last().waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: "tests/chapters-mobile.png", fullPage: true });
  await page.evaluate(() => localStorage.setItem("adminToken", "fixture-admin"));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base + "/admin/assessments/questions");
  await page.getByRole("heading", { name: "Question Bank", exact: true }).waitFor();
  assert.equal(await page.getByText("Exam year", { exact: true }).count(), 0);
  assert.equal(await page.getByText("Exam session", { exact: true }).count(), 0);
  await page.locator("button").filter({ hasText: "MCQ / Test question" }).click({ timeout: 10000 }).catch(async error => { console.log(page.url(), await page.locator("body").innerText(), errors); throw error; });
  await page.getByRole("option", { name: "Long question", exact: true }).click();
  assert.equal(await page.getByText("Exam year", { exact: true }).count(), 1);
  assert.equal(await page.getByText("Exam session", { exact: true }).count(), 1);
  assert.equal(await page.getByText("Correct Answer", { exact: true }).count(), 0);
  assert.equal(await page.getByText("Option A", { exact: true }).count(), 0);
  await page.getByPlaceholder("Question text", { exact: true }).fill("Describe motion.");
  await page.getByRole("button", { name: "Save Question" }).click();
  await page.getByText("Select the study context, including a chapter and a topic for written questions.", { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  await browser.close();
  console.log("PASS: chapter/topic links, ordered single rows, video selection, written tabs, inherited context, login redirect, scope payloads, and mobile overflow.");
})().catch(error => { console.error(error); process.exit(1); });
