const mongoose = require("mongoose");
const Chapter = require("../models/Chapter");
const Topic = require("../models/Topic");
const Assessment = require("../models/Assessment");
const mcqFilter = { contentType: { $nin: ["long_question", "short_question"] }, type: { $in: ["standard_mcq", "scenario_mcq"] }, status: { $ne: "archived" } };

async function resolveScope(chapterId, topicId) {
    const id = topicId || chapterId;
    if (!mongoose.isObjectIdOrHexString(id)) throw Object.assign(new Error("Select a valid chapter or topic."), { status: 400 });
    const topic = topicId ? await Topic.findById(topicId).lean() : null;
    if (topicId && !topic) throw Object.assign(new Error("Topic not found."), { status: 404 });
    const chapter = await Chapter.findById(topic ? topic.chapterId : chapterId).lean();
    if (!chapter) throw Object.assign(new Error("Chapter not found."), { status: 404 });
    if (topic && chapterId && String(topic.chapterId) !== chapterId) throw Object.assign(new Error("Topic does not belong to this chapter."), { status: 400 });
    const filter = { chapter: chapter._id, board: chapter.board, class: chapter.class, group: chapter.group, subject: chapter.subject };
    if (topic) filter.topic = topic._id;
    return { chapter, topic, filter };
}

async function createScopeTest(chapterId, topicId) {
    const { chapter, topic, filter } = await resolveScope(chapterId, topicId);
    const assessment = await Assessment.findOne({
        ...filter,
        type: topic ? "topic_test" : "chapter_test",
        status: "published",
        createdBy: { $exists: true },
        ...(topic ? {} : { isAutoGenerated: { $ne: true } }),
    }).sort({ createdAt: -1 }).lean();
    if (assessment || topic) {
        if (!assessment) throw Object.assign(new Error("No topic test has been published here yet."), { status: 404 });
        return assessment;
    }

    const topicTests = await Assessment.find({
        ...filter,
        type: "topic_test",
        status: "published",
        createdBy: { $exists: true },
    }).sort({ createdAt: 1 }).lean();

    const uniqueQuestions = new Map();
    topicTests.forEach((test) => {
        (test.questions || []).forEach((item) => {
            const id = String(item.question);
            if (!uniqueQuestions.has(id)) uniqueQuestions.set(id, item);
        });
    });
    const questions = [...uniqueQuestions.values()].map((item, index) => ({
        question: item.question,
        marks: item.marks || 1,
        order: index + 1,
        required: item.required !== false,
    }));
    if (!questions.length) throw Object.assign(new Error("No chapter or topic tests have been published here yet."), { status: 404 });

    const totalMarks = questions.reduce((sum, item) => sum + Number(item.marks || 1), 0);
    const durationMinutes = Math.max(1, topicTests.reduce((sum, test) => sum + Number(test.durationMinutes || 0), 0));
    const generated = await Assessment.findOneAndUpdate(
        { ...filter, type: "chapter_test", isAutoGenerated: true },
        {
            title: `${chapter.name} Complete Chapter Test`,
            description: "A complete chapter test assembled from all published topic tests.",
            ...filter,
            type: "chapter_test",
            questions,
            durationMinutes,
            totalMarks,
            passingMarks: Math.ceil(totalMarks * 0.4),
            status: "published",
            isAutoGenerated: true,
            createdBy: topicTests[0].createdBy,
        },
        { new: true, upsert: true, setDefaultsOnInsert: true }
    ).lean();
    return generated;
}

module.exports = { resolveScope, createScopeTest, mcqFilter };
